image: 
  gitpod/workspace-ruby-3.0:latest

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: true
    addLabel: prebuilt-in-gitpod

tasks:
  - init: gem install jekyll bundler
  - command: jekyll serve --watch
