title: dadatoa.github.io

description: un beau site

#baseurl: ""

show_excerpts: true

theme: minima

collections:
  sections:
    output: true
    posts:
    permalink: /:title/
    
defaults:
  - 
    scope:
      path: ""
      type: "sections"
    values:
      layout: "section"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "home"


#paginate: 5 # ajoute de la pagination (5 posts par pages)
#paginate_path: "/blog/page:num/"

github_username: dadatoa

plugins:
  - jekyll-seo-tag 
  - jemoji 
  #- jekyll-github-metadata 
  #- jekyll-avatar 
  #- jekyll-remote-theme
  #- jekyll-mentions
  #- jekyll-include-cache 
  - jekyll-readme-index 
  #- jekyll-optional-front-matter 

# exclude : contient tout les fichier non nécessaire à Jekyll pour éviter qu'ils ne soient copier ds le repertoire de deploy
exclude : [
  .jekyll-cache,
  .gitignore,
  .gitpod.Dockerfile,
  .gitpod.yml,
  docker-compose.yml,
  Gemfile,
  Gemfile.lock,
  scripts/,
  vendor/,
  ]

# disable_disk_cache: BOOL - évite la création d'un repertoire de cache type .jekyll-cache
disable_disk_cache: true

