title: dadatoa.github.io
plugins:
  - jekyll-seo-tag 
  - jemoji 
  #- jekyll-github-metadata 
  #- jekyll-avatar 
  #- jekyll-remote-theme
  #- jekyll-mentions
  #- jekyll-include-cache 
  - jekyll-readme-index 
  - jekyll-optional-front-matter 
