title: dadatoa.github.io

description: un beau site

baseurl: ""

show_excerpts: true

theme: minima

collections:
  sections:
    output: true
    permalink: /:title/
    posts:
    permalink: /:title/
    
defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"


#paginate: 5 # ajoute de la pagination (5 posts par pages)
#paginate_path: "/blog/page:num/"

github_username: dadatoa

plugins:
  - jekyll-seo-tag # SEO automatique depuis c######^#title:: un titre: dadatoa.github.ioe.#description
  - jemoji # les emoji de github pages
  - jekyll-github-metadata # personalise c######^#title: #description url et #baseurl d'après les données du repo Github si rien n'est spécifié
  - jekyll-avatar # récupere l'avatar github pour le placer ou on le souhaite sur le c######^#title:: un titre: dadatoa.github.ioe
  - jekyll-remote-theme
  - jekyll-mentions
  - jekyll-include-cache #cache les fichier includes pour améliorer un peu la vitesse de génération du c######^#title:: un titre: dadatoa.github.ioe
  - jekyll-readme-index # utilise le README du repo comme index du c######^#title:: un titre: dadatoa.github.ioe
  - jekyll-optional-front-matter # rend le frontmatter optionnel -> va chercher layout home puis page puis post par défaut

# decommenter la ligne source pour que jekyll ne compile le c######^#title:: un titre: dadatoa.github.ioe qu'à partir du contenu du dossier spécifié
# source: dossier/ 

# exclude : contient tout les fichier non nécessaire à Jekyll pour éviter qu'ils ne soient copier ds le repertoire de deploy
exclude : [
  .jekyll-cache,
  .gitignore,
  .gitpod.Dockerfile,
  .gitpod.yml,
  docker-compose.yml,
  Gemfile,
  Gemfile.lock,
  scripts,
  ]

# disable_disk_cache: BOOL - évite la création d'un repertoire de cache type .jekyll-cache
disable_disk_cache: true

