services:
  jekyll:
    build: .
    container_name: jekyll
    working_dir: /srv/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: ["bundle", "exec", "jekyll", "serve", "--watch"]
