services:
  jekyll:
    image: gitpod/ghpages # mon image perso github-pages cf -> repo dockerfiles
    command: jekyll build --watch --verbose
    volumes:
      - .:/srv/jekyll
    
  server:
    image: caddy
    ports:
      - 8080:80
    volumes:
      - ./_site:/usr/share/caddy