# config.yml

backend:
  name: github
  repo: dadatoa/dadatoa.github.io
  branch: gh-pages
local_backend: false

media_library:
  name: cloudinary
  config:
    cloud_name: daz7gamgu
    api_key: 276326737381514

#media_folder: static/images/uploads

# Publish mode
publish_mode: editorial_workflow

# Slug - personnalisation des liens
slug:
  clean_accents: true

collections:
# config site
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: 'Configuration'
        name: 'configuration'
        file: '_data/configsite.yml'
        fields:
          - label: 'Navigation'
            name: 'sections'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
     
          - label: 'Catégories de Blog'
            name: 'categories'
            widget: 'list'
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Name, name: name, widget: string }
  # Blog
  - name: "blog"
    label: "Blog"
    folder: "collections/_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", pattern: ['^.{1,280}$', "280 charactères max"] }
      - { label: "Category",name: "category", 
        widget: "relation",
        collection: "config",
        file: "configuration",
        search_fields: ["categories.*.label"],
        display_fields: ["categories.*.label"],
        value_field: "categories.*.name",
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Publish Date", name: "pubdate", widget: "datetime", date_format: "DD.MM.YYYY" }
      - { label: "Update", name: "update", widget: "boolean", default: false,}
      - { label: "Layout", name: "layout", widget: "select", options: ["post","home"], default: "post"}
      - { label: "Body", name: "body", widget: "markdown" }

 #  Docs
  - name: "docs"
    label: "Docs"
    folder: "collections/_Docs/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", pattern: ['^.{1,280}$', "280 charactères max"] }
      - { label: "Category",name: "category", 
        widget: "relation",
        collection: "config",
        file: "configuration",
        search_fields: ["categories.*.label"],
        display_fields: ["categories.*.label"],
        value_field: "categories.*.name",
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Publish Date", name: "pubdate", widget: "datetime", date_format: "DD.MM.YYYY" }
      - { label: "Update", name: "update", widget: "boolean", default: false,}
      - { label: "Layout", name: "layout", widget: "select", options: ["post","home"], default: "post"}
      - { label: "Body", name: "body", widget: "markdown" }

 # Projects
  - name: "projets"
    label: "Projets"
    folder: "collections/_projets/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", pattern: ['^.{1,280}$', "280 charactères max"] }
      - { label: "Category",name: "category", 
        widget: "relation",
        collection: "config",
        file: "configuration",
        search_fields: ["categories.*.label"],
        display_fields: ["categories.*.label"],
        value_field: "categories.*.name",
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Publish Date", name: "pubdate", widget: "datetime", date_format: "DD.MM.YYYY" }
      - { label: "Update", name: "update", widget: "boolean", default: false,}
      - { label: "Layout", name: "layout", widget: "select", options: ["post","home"], default: "post"}
      - { label: "Body", name: "body", widget: "markdown" }